### ISSUE TITLE
Coffeescript example of inheriting from EventEmitter4

### ISSUE THREAD

**Issue by ghostsquad** [eriksank/eventemitter4#3]
Can you provide a coffeescript example of how to inherit from EventEmitter4?

**Comment by eriksank** [comment]
I have never used coffeescript. I guess it is an interesting take on javascript -- the good parts -- like so many ;-)

**Comment by ghostsquad** [comment]
Actually, I decided against having my class inherit from `EventEmitter4`, instead, I have an internal property that is an instance of it, and then several methods that delegate to `on`, `emit`, `onAny`. This isn't needed, but might be useful for someone else.
